M48
; DRILL file {KiCad 7.0.7} date Tue Jan  9 13:38:51 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-09T13:38:51+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X94.108Y-60.049
X94.108Y-60.049
X99.888Y-60.049
X99.888Y-60.049
T2
X90.0Y-57.5
X90.0Y-70.0
X104.0Y-70.0
T0
M30
