M48
; DRILL file {KiCad 8.0.9} date 2025-07-19T06:53:03+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-19T06:53:03+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X3.705Y-2.3641
X3.9326Y-2.3641
T2
X2.9927Y-2.4483
X2.9927Y-2.9994
M30
